masterserver:
  container_name: "API_mysql-master"
  root_password: "root"
  database_name: "mydb"
  port_mapping: "3306:3306"
  image: "mysql:latest"


slaveserver:
  container_name: "API_mysql-slave"
  root_password: "root"
  database_name: "mydb"
  # port_mapping: "3306:3305"
  image: "mysql:latest"
