services:
    mysql-slave9:
        image: mysql:8.0
        container_name: mysql-slave9-server
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        ports:
            - 3315:3306
        volumes:
            - .\config\slave\my.cnf:/etc/mysql/my.cnf
            - mysql-slave9-data:/var/lib/mysql
        networks:
            - mysql-network
        entrypoint: bash -c "chmod 644 /etc/mysql/my.cnf && exec docker-entrypoint.sh mysqld"
volumes:
    mysql-slave9-data:
        name: mysql-slave9-data
networks:
    mysql-network:
        name: mysql-network
