services:
    master:
        image: mysql:8.0
        container_name: master-server
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: example_db
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        ports:
            - 3306:3306
        volumes:
            - .\config\master\my.cnf:/etc/mysql/my.cnf
            - master-data:/var/lib/mysql
        networks:
            - mysql-network
        entrypoint: bash -c "chmod 644 /etc/mysql/my.cnf && exec docker-entrypoint.sh mysqld"
volumes:
    master-data:
        name: master-data
networks:
    mysql-network:
        name: mysql-network
