services:
  master:
    image: mysql:8.0
    container_name: mysql-master
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: example_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - .\config\master\my.cnf:/etc/mysql/my.cnf
      - :/var/lib/mysql 
    ports:   
      - "3306:3306"
    networks:
      - mysql-network
    entrypoint:
      bash -c "chmod 644 /etc/mysql/my.cnf && exec docker-entrypoint.sh mysqld"

  slave:
    image: mysql:8.0
    container_name: mysql-slave
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - .\config\slave\my.cnf:/etc/mysql/my.cnf
      - :/var/lib/mysql
    networks:
      - mysql-network
    entrypoint: 
      bash -c "chmod 644 /etc/mysql/my.cnf && exec docker-entrypoint.sh mysqld"

volumes:
  master-data:
    name: master-data
  slave-data:
    name: slave-data

networks:
  mysql-network:
    name: mysql-network
